apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapi
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - image: fastapi-test-local:0.0.1
          name: fastapi
          ports:
            - containerPort: 5000
              hostPort: 80
              protocol: TCP
