apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi
  name: fastapi
spec:
  ports:
    - name: "fastapi-service"
      port: 80
      targetPort: 5000
      nodePort: 30007
  selector:
    app: fastapi
  type: NodePort
